Mission manager ptest case
pathfinder-for-autonomous-navigation/psim pull request #128
Opened 2020-02-28 23:43 UTC by tanishqaggarwal

To run, invoke the command

`python -m ptest.run_simulation -c ptest/configs/fc_only_native.json -t DeploymentToStandby`

from within the psim/python directory.

2020-02-29 15:54 UTC, tanishqaggarwal commented on python/ptest/cases/base.py
> +        return 'startup'
We should try to wrap these properties up into a struct @nhz2 @kkrol27

2020-03-01 22:57 UTC, nhz2 requested changes

2020-03-01 22:57 UTC, nhz2 commented on MATLAB/sensor_reading.m
> +sensor_readings.position_ecef= position_ecef;
This should be in an if statement controlled by a variable in const, that way it won't break the matlab sim.

2020-03-03 20:25 UTC, nhz2 approved these changes

2020-03-05 22:40 UTC, kylekrol approved these changes

2020-03-06 04:25 UTC, kkrol27 commented
@tanishqaggarwal What's the story here with this PR and the PTest merger into FSW?

2020-03-06 21:34 UTC, tanishqaggarwal commented
Closing because the change has moved to FlightSoftware.

2020-03-06 21:34 UTC, closed without merging