updated environment model docs and added gravity model
pathfinder-for-autonomous-navigation/psim pull request #209
Opened 2020-05-09 21:45 UTC by kkrol27

# Update Environment Model Docs and Add Gravity Model

### Summary of changes
- Added a 4th order gravity model (like MATLAB) to the GNC environment models. This will be used soon for the orbit controller implementation and we don't quite need the accuracy orbit estimation requires.
- Updated the documentation for the environment models to conform better with doxygen. I wrapped them up in an environment module and will do the same for the utility functions, attitude estimator, etc soon.

### Ptest Effects
NA

### Testing
I added a unit test comparing the model to MATLAB. Given this essentially calls the same exact model, however, there isn't a huge need for testing other than the spot checking added here.

### Constants

| Constant                 | Location             |
|--------------------------|----------------------|
|              env_grav_order            |       src/gnc_environment.cpp         |

### Documentation Evidence
Inline docs should be good.

2020-05-10 01:13 UTC, nhz2 commented on include/gnc/environment.hpp
> + *  @param[out] w_eci Earth's angular rate (units of radians per second).
```suggestion
 *  @param[out] w_ecef Earth's angular rate (units of radians per second).
```

2020-05-10 01:13 UTC, nhz2 commented on include/gnc/environment.hpp
> +void earth_angular_rate(double t, lin::Vector3d &w_eci);
```suggestion
void earth_angular_rate(double t, lin::Vector3d &w_ecef);
```

2020-05-10 01:14 UTC, nhz2 commented on include/gnc/environment.hpp
> + *  @param[out] w_eci Earth's angular rate (units of radians per second).
```suggestion
 *  @param[out] w_ecef Earth's angular rate (units of radians per second).
```

2020-05-10 01:14 UTC, nhz2 commented on include/gnc/environment.hpp
> +void earth_angular_rate(double t, lin::Vector3f &w_eci);
```suggestion
void earth_angular_rate(double t, lin::Vector3f &w_ecef);
```

2020-05-10 01:18 UTC, nhz2 commented on include/gnc/environment.hpp
> + *  @param[out] w_eci Earth's angular rate (units of radians per second).
```suggestion
 *  @param[out] w_ecef Earth's angular rate (units of radians per second).
```

2020-05-10 01:21 UTC, nhz2 commented on include/gnc/environment.hpp
> + *  rate about the z-axis and doesn't model precession/nutation.
[Polar motion](https://en.wikipedia.org/wiki/Polar_motion) not precession/nutation

2020-05-10 01:38 UTC, nhz2 requested changes
This isn't compiling for teesny36 for me.
```
test/test_all/environment_test.cpp: In function 'void test_environment_earth_attitude()':
test/test_all/environment_test.cpp:10:17: error: no matching function for call to 'lin::Vector<double, 3u, 3u>::Vector()'
   lin::Vector3d w;
                 ^
In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
                 from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
                 from lib/lin/include/lin/core/operations.hpp:23,
                 from lib/lin/include/lin/core.hpp:18,
                 from include/gnc/config.hpp:9,
                 from include/gnc/constants.hpp:8,
                 from test/test_all/environment_test.cpp:5:
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: constexpr lin::Vector<double, 3u, 3u>::Vector(lin::size_t, lin::size_t)
   using internal::Tensor<Vector<T, N, MN>>::Tensor;
                                             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   candidate expects 2 arguments, 0 provided
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class T> constexpr lin::Vector<double, 3u, 3u>::Vector(const std::initializer_list<_Tp>&)
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
test/test_all/environment_test.cpp:10:17: note:   candidate expects 1 argument, 0 provided
   lin::Vector3d w;
                 ^
In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
                 from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
                 from lib/lin/include/lin/core/operations.hpp:23,
                 from lib/lin/include/lin/core.hpp:18,
                 from include/gnc/config.hpp:9,
                 from include/gnc/constants.hpp:8,
                 from test/test_all/environment_test.cpp:5:
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class T> constexpr lin::Vector<double, 3u, 3u>::Vector(lin::size_t, lin::size_t, const std::initializer_list<_Tp>&)
   using internal::Tensor<Vector<T, N, MN>>::Tensor;
                                             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
test/test_all/environment_test.cpp:10:17: note:   candidate expects 3 arguments, 0 provided
   lin::Vector3d w;
                 ^
In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
                 from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
                 from lib/lin/include/lin/core/operations.hpp:23,
                 from lib/lin/include/lin/core.hpp:18,
                 from include/gnc/config.hpp:9,
                 from include/gnc/constants.hpp:8,
                 from test/test_all/environment_test.cpp:5:
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class C> constexpr lin::Vector<double, 3u, 3u>::Vector(const lin::internal::Stream<C>&)
   using internal::Tensor<Vector<T, N, MN>>::Tensor;
                                             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
test/test_all/environment_test.cpp:10:17: note:   candidate expects 1 argument, 0 provided
   lin::Vector3d w;
                 ^
In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
                 from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
                 from lib/lin/include/lin/core/operations.hpp:23,
                 from lib/lin/include/lin/core.hpp:18,
                 from include/gnc/config.hpp:9,
                 from include/gnc/constants.hpp:8,
                 from test/test_all/environment_test.cpp:5:
lib/lin/include/lin/core/operations/../types/vector.hpp:97:13: note: candidate: template<class U> constexpr lin::Vector<T, N, MN>::Vector(lin::size_t, const std::initializer_list<T>&)
   constexpr Vector(size_t n, std::initializer_list<U> const &list)
             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:97:13: note:   template argument deduction/substitution failed:
test/test_all/environment_test.cpp:10:17: note:   candidate expects 2 arguments, 0 provided
   lin::Vector3d w;
                 ^
In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
                 from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
                 from lib/lin/include/lin/core/operations.hpp:23,
                 from lib/lin/include/lin/core.hpp:18,
                 from include/gnc/config.hpp:9,
                 from include/gnc/constants.hpp:8,
                 from test/test_all/environment_test.cpp:5:
lib/lin/include/lin/core/operations/../types/vector.hpp:80:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(lin::size_t) [with T = double; unsigned int N = 3u; unsigned int MN = 3u; lin::size_t = unsigned int]
   constexpr Vector(size_t n)
             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:80:13: note:   candidate expects 1 argument, 0 provided
lib/lin/include/lin/core/operations/../types/vector.hpp:65:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(lin::Vector<T, N, MN>&&) [with T = double; unsigned int N = 3u; unsigned int MN = 3u]
   constexpr Vector(Vector<T, N, MN> &&) = default;
             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:65:13: note:   candidate expects 1 argument, 0 provided
lib/lin/include/lin/core/operations/../types/vector.hpp:64:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(const lin::Vector<T, N, MN>&) [with T = double; unsigned int N = 3u; unsigned int MN = 3u]
   constexpr Vector(Vector<T, N, MN> const &) = default;
             ^
lib/lin/include/lin/core/operations/../types/vector.hpp:64:13: note:   candidate expects 1 argument, 0 provided
```

2020-05-10 01:47 UTC, kkrol27 commented
> This isn't compiling for teesny36 for me.
> 
> ```
> test/test_all/environment_test.cpp: In function 'void test_environment_earth_attitude()':
> test/test_all/environment_test.cpp:10:17: error: no matching function for call to 'lin::Vector<double, 3u, 3u>::Vector()'
>    lin::Vector3d w;
>                  ^
> In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
>                  from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
>                  from lib/lin/include/lin/core/operations.hpp:23,
>                  from lib/lin/include/lin/core.hpp:18,
>                  from include/gnc/config.hpp:9,
>                  from include/gnc/constants.hpp:8,
>                  from test/test_all/environment_test.cpp:5:
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: constexpr lin::Vector<double, 3u, 3u>::Vector(lin::size_t, lin::size_t)
>    using internal::Tensor<Vector<T, N, MN>>::Tensor;
>                                              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   candidate expects 2 arguments, 0 provided
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class T> constexpr lin::Vector<double, 3u, 3u>::Vector(const std::initializer_list<_Tp>&)
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
> test/test_all/environment_test.cpp:10:17: note:   candidate expects 1 argument, 0 provided
>    lin::Vector3d w;
>                  ^
> In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
>                  from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
>                  from lib/lin/include/lin/core/operations.hpp:23,
>                  from lib/lin/include/lin/core.hpp:18,
>                  from include/gnc/config.hpp:9,
>                  from include/gnc/constants.hpp:8,
>                  from test/test_all/environment_test.cpp:5:
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class T> constexpr lin::Vector<double, 3u, 3u>::Vector(lin::size_t, lin::size_t, const std::initializer_list<_Tp>&)
>    using internal::Tensor<Vector<T, N, MN>>::Tensor;
>                                              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
> test/test_all/environment_test.cpp:10:17: note:   candidate expects 3 arguments, 0 provided
>    lin::Vector3d w;
>                  ^
> In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
>                  from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
>                  from lib/lin/include/lin/core/operations.hpp:23,
>                  from lib/lin/include/lin/core.hpp:18,
>                  from include/gnc/config.hpp:9,
>                  from include/gnc/constants.hpp:8,
>                  from test/test_all/environment_test.cpp:5:
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note: candidate: template<class C> constexpr lin::Vector<double, 3u, 3u>::Vector(const lin::internal::Stream<C>&)
>    using internal::Tensor<Vector<T, N, MN>>::Tensor;
>                                              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:54:45: note:   template argument deduction/substitution failed:
> test/test_all/environment_test.cpp:10:17: note:   candidate expects 1 argument, 0 provided
>    lin::Vector3d w;
>                  ^
> In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
>                  from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
>                  from lib/lin/include/lin/core/operations.hpp:23,
>                  from lib/lin/include/lin/core.hpp:18,
>                  from include/gnc/config.hpp:9,
>                  from include/gnc/constants.hpp:8,
>                  from test/test_all/environment_test.cpp:5:
> lib/lin/include/lin/core/operations/../types/vector.hpp:97:13: note: candidate: template<class U> constexpr lin::Vector<T, N, MN>::Vector(lin::size_t, const std::initializer_list<T>&)
>    constexpr Vector(size_t n, std::initializer_list<U> const &list)
>              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:97:13: note:   template argument deduction/substitution failed:
> test/test_all/environment_test.cpp:10:17: note:   candidate expects 2 arguments, 0 provided
>    lin::Vector3d w;
>                  ^
> In file included from lib/lin/include/lin/core/operations/../types.hpp:23:0,
>                  from lib/lin/include/lin/core/operations/tensor_operations.hpp:12,
>                  from lib/lin/include/lin/core/operations.hpp:23,
>                  from lib/lin/include/lin/core.hpp:18,
>                  from include/gnc/config.hpp:9,
>                  from include/gnc/constants.hpp:8,
>                  from test/test_all/environment_test.cpp:5:
> lib/lin/include/lin/core/operations/../types/vector.hpp:80:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(lin::size_t) [with T = double; unsigned int N = 3u; unsigned int MN = 3u; lin::size_t = unsigned int]
>    constexpr Vector(size_t n)
>              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:80:13: note:   candidate expects 1 argument, 0 provided
> lib/lin/include/lin/core/operations/../types/vector.hpp:65:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(lin::Vector<T, N, MN>&&) [with T = double; unsigned int N = 3u; unsigned int MN = 3u]
>    constexpr Vector(Vector<T, N, MN> &&) = default;
>              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:65:13: note:   candidate expects 1 argument, 0 provided
> lib/lin/include/lin/core/operations/../types/vector.hpp:64:13: note: candidate: constexpr lin::Vector<T, N, MN>::Vector(const lin::Vector<T, N, MN>&) [with T = double; unsigned int N = 3u; unsigned int MN = 3u]
>    constexpr Vector(Vector<T, N, MN> const &) = default;
>              ^
> lib/lin/include/lin/core/operations/../types/vector.hpp:64:13: note:   candidate expects 1 argument, 0 provided
> ```

I'll have to break my teensy out and look into this.

2020-05-10 19:39 UTC, kkrol27 commented
@nhz2 The build issue will be fixed by #220

2020-05-11 05:47 UTC, nhz2 approved these changes

2020-05-11 06:42 UTC, merged