Dual Orbit Simulation
pathfinder-for-autonomous-navigation/psim pull request #254
Opened 2020-10-11 21:56 UTC by kkrol27

Small PR to add a simulation where we model two satellites and their orbital mechanics. No attitude dynamics or attitude related actuators are included.

2020-10-11 21:58 UTC, kkrol27 commented on src/psim/simulations/single_orbit.cpp
> +  add<TransformPositionEci>(config, "truth", "truth.leader.environment.s");
These two lines here make the following transformations:

 * `truth.leader.environment.b` into `truth.eader.environment.b.eci` and `truth.eader.environment.b.ecef`
 * `truth.eader.environment.s` into `truth.eader.environment.s.eci` and `truth.eader.environment.s.ecef`

2020-10-11 21:59 UTC, kkrol27 commented on python/psim/sims.py
> +    DualOrbitGnc,
Here is where we make the new simulation type available for use in Python.

2020-10-11 22:00 UTC, kkrol27 commented on python/psim/_psim/simulations.cpp
> +  PY_SIMULATION(DualOrbitGnc);
Wrapping the new model as a simulation available in Python.

2020-10-13 15:07 UTC, tanishqaggarwal requested changes

2020-10-13 15:07 UTC, tanishqaggarwal commented on src/psim/simulations/dual_orbit.cpp
> +DualOrbitGnc::DualOrbitGnc(Configuration const &config) {
Seems like it should be possible to make this code reusable for the SingleOrbit case. As sensor models, etc. develop I'm worried about a lot of code copying occurring across the single and dual-orbit GNC.

2020-10-13 19:43 UTC, kylekrol commented on src/psim/simulations/dual_orbit.cpp
> +DualOrbitGnc::DualOrbitGnc(Configuration const &config) {
This is a good point. I'll break it out into a `SatelliteOrbitGnc` model that's shared across both cases.

2020-10-15 19:52 UTC, kkrol27 commented on python/psim/_psim/simulations.cpp
> +};
This allows different simulations to be exposed as different objects in Python.

2020-10-18 19:40 UTC, tanishqaggarwal approved these changes
Looks like a solid restructure.

2020-10-19 16:51 UTC, merged